const cli = require('commander');

cli
  .command('*')
  .option('-o, --output', 'Write the result to the file at path OUTPUT.')
  .option('-a, --armor', 'Encrypt to a PEM encoded format.')
  .option('-p, --passphrase', 'Encrypt with a passphrase.')
  .option('-r, --recipient <RECIPIENT>', 'Encrypt to the specified RECIPIENT. Can be repeated.')
  .option('-i, --identity <KEY>', 'Use the private key file at path KEY. Can be repeated.')
  .action(function(_input) {
    const input = cli.args[0];
    console.log(input)
  });

cli.on('--help', () => {
  console.log(`
INPUT defaults to standard input, and OUTPUT defaults to standard output.

RECIPIENT can be an age public key, as generated by age-keygen, ("age1...")
or an SSH public key ("ssh-ed25519 AAAA...", "ssh-rsa AAAA...").

KEY is a path to a file with age secret keys, one per line
(ignoring "#" prefixed comments and empty lines), or to an SSH key file.
Multiple keys can be provided, and any unused ones will be ignored.
  `);
})

cli.parse(process.argv);
// if (cli.debug)
